### PR TITLE
Add Entry or_default

### PR DESCRIPTION
**Pull request by camsteffen**
Docs and implementation are basically copied from HashMap.

### CODE REVIEW

**Comment by camsteffen** [comment]
@Gankra Any concerns preventing this from getting merged?

**Comment by clarfonthey** [comment]
Did you read the readme?

**Comment by camsteffen** [comment]
Yes. I interpreted it to mean that minor improvements with "minimal review requirements" _might_ be accepted. But I respect the owner's right to do what they want.

**Comment by camsteffen** [comment]
This doesn't seem to have any chance of being merged.

**Pull request closed without merging**
